import "@/app/globals.css"; // Ensure to import the global styles for the user layout
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../header/Header";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "SELLNITY-Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
